// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using RallyeTime.Persistence;
using System;

namespace rallyetimenetcoreapi.Migrations
{
    [DbContext(typeof(RallyeDbContext))]
    partial class RallyeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("RallyeTime.Models.Checkpoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250);

                    b.Property<int?>("Points");

                    b.Property<int>("RaceId");

                    b.Property<string>("TimeActual")
                        .HasMaxLength(250);

                    b.Property<string>("TimeError")
                        .HasMaxLength(250);

                    b.Property<DateTime?>("TimeIn");

                    b.Property<DateTime?>("TimeOut");

                    b.Property<string>("TimeTrue")
                        .HasMaxLength(250);

                    b.HasKey("Id");

                    b.HasIndex("RaceId");

                    b.ToTable("Checkpoints");
                });

            modelBuilder.Entity("RallyeTime.Models.Race", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AccessCode")
                        .IsRequired()
                        .HasMaxLength(250);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250);

                    b.HasKey("Id");

                    b.ToTable("Races");
                });

            modelBuilder.Entity("RallyeTime.Models.Checkpoint", b =>
                {
                    b.HasOne("RallyeTime.Models.Race")
                        .WithMany("Checkpoints")
                        .HasForeignKey("RaceId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
